import { writeFileSync } from 'node:fs';

const demo = process.env.BDENTAL_DEMO === '1' || process.env.BDENTAL_DEMO === 'true';
const config = { demo };

writeFileSync(
  new URL('./public/config.js', import.meta.url),
  `// Generated by build.js — do not edit.\nwindow.BDENTAL_CONFIG = ${JSON.stringify(config)};\n`
);

console.log(`[build] wrote public/config.js (demo=${demo})`);
